### ISSUE TITLE
Error Acessing docs from Google Drive

### ISSUE THREAD

**Issue by tobiastromm** [HBiSoft/PickiT#15]
Hi.

Any .doc file I try to upload from drive I getting error.

If file is image or pdf is ok.

Try several files.

Can someone confirm please.

`2020-04-07 19:56:58.133 7276-7788/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3Dencoded%3D%2F2UAjJF6sM03B39hXL5nCqpt0ccgmnJO%2BWip%2FsaCpZPuDWXQVA%3D%3D from pid=6564, uid=10231 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:634)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:735)
    
    
    --------- beginning of crash
2020-04-07 19:56:58.166 6564-7789/com.papinho E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
    Process: com.papinho, PID: 6564
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.SecurityException: Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3Dencoded%3D%2F2UAjJF6sM03B39hXL5nCqpt0ccgmnJO%2BWip%2FsaCpZPuDWXQVA%3D%3D from pid=6564, uid=10231 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:802)
        at android.content.ContentResolver.query(ContentResolver.java:752)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at com.hbisoft.pickit.DownloadAsyncTask.getFileName(DownloadAsyncTask.java:119)
        at com.hbisoft.pickit.DownloadAsyncTask.doInBackground(DownloadAsyncTask.java:79)
        at com.hbisoft.pickit.DownloadAsyncTask.doInBackground(DownloadAsyncTask.java:18)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
`

**Comment by HBiSoft** [comment]
The issue is described in the log:

    Caused by: java.lang.SecurityException: Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3Dencoded%3D%2F2UAjJF6sM03B39hXL5nCqpt0ccgmnJO%2BWip%2FsaCpZPuDWXQVA%3D%3D from pid=6564, uid=10231 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

You should use `ACTION_OPEN_DOCUMENT` instead of `ACTION_GET_CONTENT`

This issue was already opened here - https://github.com/HBiSoft/PickiT/issues/10
