### ISSUE TITLE
java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider

### ISSUE THREAD

**Issue by milan-galitein** [HBiSoft/PickiT#51]
**Describe the bug**
- I am getting crash log from live App.

**Log**
`java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.impl.MediaContentProvider from ProcessRecord{c17cc1b 26188:com.einpix.android/u0a165} (pid=26188, uid=10165) that is not exported from UID 10143
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
    at android.os.Parcel.createException(Parcel.java:2357)
    at android.os.Parcel.readException(Parcel.java:2340)
    at android.os.Parcel.readException(Parcel.java:2282)
    at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5736)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:6877)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2936)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
    at android.content.ContentResolver.query(ContentResolver.java:1167)
    at android.content.ContentResolver.query(ContentResolver.java:1115)
    at android.content.ContentResolver.query(ContentResolver.java:1071)
    at com.hbisoft.pickit.DownloadAsyncTask.doInBackground(SourceFile:62)
    at com.hbisoft.pickit.DownloadAsyncTask.doInBackground(SourceFile:19)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)`

**Can it be reproduced in demo app**
No

**PickiT version**
for example 0.1.14

**Device information**
- WP5 Pro/RP1A.200720.011
- Android 11

**Comment by HBiSoft** [comment]
With the limited amount of information provided, I can only presume your issue is related to [this](https://stackoverflow.com/a/43398935/5550161).
